"""Type stubs for the bellmaneq._core Rust extension module."""

import numpy as np
from numpy.typing import NDArray

class PySolverResult:
    """Result returned by MDP solvers."""

    iterations: int
    converged: bool

    def get_values(self) -> NDArray[np.float64]: ...
    def get_policy(self) -> NDArray[np.int64]: ...
    def get_convergence_history(self) -> NDArray[np.float64]: ...

def solve_value_iteration(
    rewards: NDArray[np.float64],
    transitions: NDArray[np.float64],
    gamma: float,
    tol: float = 1e-10,
    max_iter: int = 10000,
) -> PySolverResult: ...

def solve_policy_iteration(
    rewards: NDArray[np.float64],
    transitions: NDArray[np.float64],
    gamma: float,
) -> PySolverResult: ...

class PyTicTacToe:
    """Tic-Tac-Toe game engine with minimax search."""

    def __init__(self) -> None: ...
    def minimax(self, board: list[int], next_player: int, depth: int) -> float: ...
    def best_move(self, board: list[int], next_player: int, depth: int) -> int | None: ...
    def legal_actions(self, board: list[int], next_player: int) -> list[int]: ...

class PyConnectFour:
    """Connect Four game engine with minimax search."""

    def __init__(self) -> None: ...
    def minimax(self, board: list[list[int]], next_player: int, depth: int) -> float: ...
    def best_move(self, board: list[list[int]], next_player: int, depth: int) -> int | None: ...
    def legal_actions(self, board: list[list[int]], next_player: int) -> list[int]: ...
    def apply_move(self, board: list[list[int]], next_player: int, col: int) -> list[list[int]]: ...
    def check_winner(self, board: list[list[int]]) -> int: ...
    @staticmethod
    def empty_board() -> list[list[int]]: ...

class PyAmericanOptionResult:
    """Result of American option pricing."""

    @property
    def price(self) -> float: ...
    def get_exercise_boundary(self) -> NDArray[np.float64]: ...
    def get_time_steps(self) -> NDArray[np.float64]: ...
    def get_stock_prices_at_maturity(self) -> NDArray[np.float64]: ...

def price_american_option(
    spot: float,
    strike: float,
    rate: float,
    volatility: float,
    maturity: float,
    steps: int,
    is_call: bool = False,
) -> PyAmericanOptionResult: ...
